### ISSUE TITLE
Use of unknown material

### ISSUE THREAD

**Issue by cchaduka** [SuperMoudy/C-programming-A-Modern-Approach-2nd-ed-Solutions#1]
Your solution to [Chap. 5, Project 8](https://github.com/SuperMoudy/C-programming-A-Modern-Approach-2nd-ed-Solutions/blob/master/Ch05_Selection_Statements/ch5_prog_proj_08.c) uses arrays. At this stage, the scholar doesn't know what an array is.

**Comment by SuperMoudy** [comment]
Thank you for reporting this. I've just added a new solution assuming no knowledge of arrays.

> Your solution to [Chap. 5, Project 8](https://github.com/SuperMoudy/C-programming-A-Modern-Approach-2nd-ed-Solutions/blob/master/Ch05_Selection_Statements/ch5_prog_proj_08.c) uses arrays. At this stage, the scholar doesn't know what an array is.

**Comment by cchaduka** [comment]
Sorry if I am being a pain, but still, they don't know the stdlib.h as well, so can't use the abs() function as well.

**Comment by SuperMoudy** [comment]
> Sorry if I am being a pain, but still, they don't know the stdlib.h as well, so can't use the abs() function as well.

Haha, it's okay ^_^ 
I updated the project once more.
You are also welcome to contribute to this project (Check the newly added README.md where you can monitor the project progress and how to contribute to the repo).

**Comment by cchaduka** [comment]
Awesome, will try my best to contribute!
